<a href="https://colab.research.google.com/github/RifatMuhtasim/Deep_Learning/blob/main/12_Gradient_Descent_For_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow import keras
import tensorflow as tf

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/DeepLearningML/6_gradient_descent/insurance_data.csv")
df.shape

(28, 3)

In [3]:
df.head(10)

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1
5   56              1                 1
6   55              0                 0
7   60              0                 1
8   62              1                 1
9   61              1                 1

In [4]:
# Transform Data
X = df.drop(['bought_insurance'], axis="columns")
y = df['bought_insurance']

X['age'] = X['age'] / 100

In [5]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# Using Tensorflow

In [6]:
# Model Building
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation="sigmoid", kernel_initializer = "ones", bias_initializer="zeros")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(X, y, epochs = 5000)

Epoch 1/1000
1/1 [==============================] - 1s 619ms/step - loss: 0.7160 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 18ms/step - loss: 0.7156 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 15ms/step - loss: 0.7152 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.7148 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.7144 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.7140 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.7136 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 21ms/step - loss: 0.7132 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 16ms/step - loss: 0.7128 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.7124 - accuracy: 0.5000
Epoch 11

In [7]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 1s 725ms/step - loss: 0.7149 - accuracy: 0.5000


[0.7148943543434143, 0.5]

In [8]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 408ms/step


array([[0.63664824],
       [0.55365694],
       [0.4059465 ],
       [0.49732774],
       [0.6479835 ],
       [0.6394969 ]], dtype=float32)

In [9]:
y_test

27    0
19    0
16    1
6     0
24    1
2     1
Name: bought_insurance, dtype: int64

In [10]:
coef, intercept = model.get_weights()
coef, intercept

(array([[1.2335299],
        [0.6825526]], dtype=float32),
 array([-0.6891305], dtype=float32))

In [15]:
def Prediction_function(age, affordability):
  weighted_sum = ((age / 100)  * coef[0]) + affordability * coef[1] + intercept
  return weighted_sum[0]

In [12]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [16]:
Prediction_function(22, 1)

0.2647987

In [17]:
Prediction_function(47, 1)

0.5731812

# Manual Python Coding

In [29]:
def Log_loss(y_true, y_pred):
  epsilon = 1e-15
  y_pred_new = [max(i, epsilon) for i in y_pred]
  y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
  y_pred_new = np.array(y_pred_new)
  result = -np.mean(y_true * np.log(y_pred_new) + (1-y_true)*np.log(1-y_pred_new))
  return result

In [30]:
def Sigmoid(X):
  result = 1 / (1+np.exp(-X))
  return result

In [31]:
def Gradient_descent(age, affordability, y_true, epochs, loss_threshold):
  w1 = w2 = 1
  bias = 0
  learning_rate = 0.01
  n = len(age)

  for i in range(epochs):
    weighted_sum = w1*age + w2*affordability + bias
    y_pred = Sigmoid(weighted_sum)
    loss = Log_loss(y_true, y_pred)
    w1d = (1/n) * np.dot(np.transpose(age), (y_pred-y_true))
    w2d = (1/n) * np.dot(np.transpose(affordability), (y_pred - y_true))
    bias_d = np.mean(y_pred - y_true)

    w1 = w1 - learning_rate * w1d
    w2 = w2 - learning_rate * w2d
    bias = bias - learning_rate * bias_d

    # if loss <= loss_threshold:
    #   break

    print(f"Epochs: {epochs}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}")
  return w1, w2, bias

In [32]:
Gradient_descent(X_train['age'], X_train['affordibility'], y_train, 1000, 0.4631)

Epochs: 1000, w1: 0.9996559982585969, w2: 0.9990565841967777, bias: -0.0023461719492531507, loss: 0.6790992381395301
Epochs: 1000, w1: 0.9993141513585498, w2: 0.9981168296445907, bias: -0.004686788228051092, loss: 0.6784488100614332
Epochs: 1000, w1: 0.9989744567207537, w2: 0.9971807331505372, bias: -0.0070218560852548986, loss: 0.6778018195878256
Epochs: 1000, w1: 0.9986369117418161, w2: 0.9962482914691542, bias: -0.009351382827180456, loss: 0.6771582527767163
Epochs: 1000, w1: 0.9983015137942333, w2: 0.9953195013027267, bias: -0.011675375817142297, loss: 0.6765180956825471
Epochs: 1000, w1: 0.9979682602265653, w2: 0.9943943593016007, bias: -0.013993842474996208, loss: 0.6758813343568805
Epochs: 1000, w1: 0.997637148363613, w2: 0.9934728620644966, bias: -0.01630679027668068, loss: 0.6752479548490842
Epochs: 1000, w1: 0.9973081755065949, w2: 0.9925550061388254, bias: -0.018614226753757235, loss: 0.6746179432070101
Epochs: 1000, w1: 0.9969813389333253, w2: 0.9916407880210064, bias: -0.0

(1.193953049159134, 0.9741713376811509, -0.9574320735748804)