<a href="https://colab.research.google.com/github/RifatMuhtasim/Deep_Learning/blob/main/Learn/10.Matrix_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
revenue = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])
revenue

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [3]:
price_per_unit = np.array([20, 30, 15])
price_per_unit

array([20, 30, 15])

In [4]:
units_sold = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
units_sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

## Calculation

**Revenue in Taka:**

In [5]:
revenue_in_taka = revenue * 110
revenue_in_taka

array([[22000, 24200, 27500],
       [ 7480,  8690, 11550],
       [12100, 15400, 19800],
       [ 8800,  9350,  9900]])

In [6]:
total = price_per_unit * units_sold
total

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])

In [7]:
total_sales = np.dot(price_per_unit , units_sold)
total_sales

array([1900, 2640, 1430])