<a href="https://colab.research.google.com/github/RifatMuhtasim/Deep_Learning/blob/main/Learn/13.Neural_Network_In_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow import keras
import tensorflow as tf

In [64]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/DeepLearningML/6_gradient_descent/insurance_data.csv")
df.shape

(28, 3)

In [65]:
df.head(10)

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1
5   56              1                 1
6   55              0                 0
7   60              0                 1
8   62              1                 1
9   61              1                 1

In [66]:
# Transform Data
X = df.drop(['bought_insurance'], axis="columns")
y = df['bought_insurance']

X['age'] = X['age'] / 100

In [67]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# Using Tensorflow

In [68]:
# Model Building
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation="sigmoid", kernel_initializer = "ones", bias_initializer="zeros")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(X, y, epochs = 5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 5ms/step - loss: 0.5167 - accuracy: 0.8571
Epoch 2502/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.5167 - accuracy: 0.8571
Epoch 2503/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.5167 - accuracy: 0.8571
Epoch 2504/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.5166 - accuracy: 0.8571
Epoch 2505/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.5166 - accuracy: 0.8571
Epoch 2506/5000
1/1 [==============================] - 0s 7ms/step - loss: 0.5165 - accuracy: 0.8571
Epoch 2507/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.5165 - accuracy: 0.8571
Epoch 2508/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.5164 - accuracy: 0.8571
Epoch 2509/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.5164 - accuracy: 0.8571
Epoch 2510/5000
1/1 [==============================] - 0

In [69]:
model.evaluate(X_test, y_test)

1/1 [==============================] - 0s 155ms/step - loss: 0.3309 - accuracy: 1.0000


[0.3309079706668854, 1.0]

In [70]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 59ms/step


array([[0.7028834 ],
       [0.11708131],
       [0.8388431 ],
       [0.5337199 ],
       [0.3885927 ],
       [0.80835515]], dtype=float32)

In [71]:
y_test

2     1
18    0
8     1
7     1
0     0
17    1
Name: bought_insurance, dtype: int64

In [72]:
coef, intercept = model.get_weights()
coef, intercept

(array([[5.257192 ],
        [1.4094174]], dtype=float32),
 array([-3.019231], dtype=float32))

In [73]:
def Prediction_function(age, affordability):
  weighted_sum = ((age / 100)  * coef[0]) + affordability * coef[1] + intercept
  return weighted_sum[0]

In [74]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [75]:
Prediction_function(22, 1)

-0.45323157

In [76]:
Prediction_function(47, 1)

0.8610666

# Manual Python Coding

In [77]:
def Log_loss(y_true, y_pred):
  epsilon = 1e-15
  y_pred_new = [max(i, epsilon) for i in y_pred]
  y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
  y_pred_new = np.array(y_pred_new)
  result = -np.mean(y_true * np.log(y_pred_new) + (1-y_true)*np.log(1-y_pred_new))
  return result

In [78]:
def Sigmoid(X):
  result = 1 / (1+np.exp(-X))
  return result

In [79]:
def Gradient_descent(age, affordability, y_true, epochs, loss_threshold):
  w1 = w2 = 1
  bias = 0
  learning_rate = 0.01
  n = len(age)

  for i in range(epochs):
    weighted_sum = w1*age + w2*affordability + bias
    y_pred = Sigmoid(weighted_sum)
    loss = Log_loss(y_true, y_pred)
    w1d = (1/n) * np.dot(np.transpose(age), (y_pred-y_true))
    w2d = (1/n) * np.dot(np.transpose(affordability), (y_pred - y_true))
    bias_d = np.mean(y_pred - y_true)

    w1 = w1 - learning_rate * w1d
    w2 = w2 - learning_rate * w2d
    bias = bias - learning_rate * bias_d

    if i%100 == 0:
      print(f"Epochs: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}")

    if loss <= loss_threshold:
      print(f"Epochs: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}")
      break

  return w1, w2, bias

In [80]:
Gradient_descent(X_train['age'], X_train['affordibility'], y_train, 100000, 0.4631)

Epochs: 0, w1: 0.999292659958375, w2: 0.9986211333979005, bias: -0.002783121915188381, loss: 0.7619600028453903
Epochs: 100, w1: 0.941706552556238, w2: 0.8843676333811648, bias: -0.24657461572860997, loss: 0.6852090437850271
Epochs: 200, w1: 0.9072253940993811, w2: 0.8123622883456594, bias: -0.43008778933657643, loss: 0.6445647496037267
Epochs: 300, w1: 0.8905541770378377, w2: 0.7732792422482426, bias: -0.5674039089368744, loss: 0.6235884874764943
Epochs: 400, w1: 0.8866690182139638, w2: 0.7577106177939896, bias: -0.6715833952214005, loss: 0.6123250180601414
Epochs: 500, w1: 0.8916217256393004, w2: 0.7580849307948224, bias: -0.7527721627771985, loss: 0.6056380035701807
Epochs: 600, w1: 0.9025720198451935, w2: 0.7689020946348529, bias: -0.818222152769187, loss: 0.6010850762638486
Epochs: 700, w1: 0.9175611677034967, w2: 0.7863593092728112, bias: -0.8729167129225103, loss: 0.5975492681676184
Epochs: 800, w1: 0.9352654090990593, w2: 0.8078927076499592, bias: -0.920218039087977, loss: 0.59

(4.636902092145374, 1.8583157291208259, -3.30768537179277)

# Building Neural Network

In [81]:
class My_Neural_Network:
  def __init__(self):
    self.w1 = 1
    self.w2 = 1
    self.bias = 0

  def fit(self, X, y, epochs, loss_threshold):
    self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_threshold)

  def predict(self, X_test):
    weighted_sum = self.w1 * X_test['age'] + self.w2 * X_test['affordibility'] + self.bias
    return Sigmoid(weighted_sum)

  def gradient_descent(self, age, affordability, y_true, epochs, loss_threshold):
    w1 = w2 = 1
    bias = 0
    learning_rate = 0.01
    n = len(age)

    for i in range(epochs):
      weighted_sum = w1*age + w2*affordability + bias
      y_pred = Sigmoid(weighted_sum)
      loss = Log_loss(y_true, y_pred)
      w1d = (1/n) * np.dot(np.transpose(age), (y_pred-y_true))
      w2d = (1/n) * np.dot(np.transpose(affordability), (y_pred - y_true))
      bias_d = np.mean(y_pred - y_true)

      w1 = w1 - learning_rate * w1d
      w2 = w2 - learning_rate * w2d
      bias = bias - learning_rate * bias_d

      if i%100 == 0:
        print(f"Epochs: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}")

      if loss <= loss_threshold:
        print(f"Epochs: {i}, w1: {w1}, w2: {w2}, bias: {bias}, loss: {loss}")
        break

    return w1, w2, bias

In [82]:
custom_model = My_Neural_Network()
custom_model.fit(X_train, y_train, epochs=1000000, loss_threshold= 0.4349)

Epochs: 0, w1: 0.999292659958375, w2: 0.9986211333979005, bias: -0.002783121915188381, loss: 0.7619600028453903
Epochs: 100, w1: 0.941706552556238, w2: 0.8843676333811648, bias: -0.24657461572860997, loss: 0.6852090437850271
Epochs: 200, w1: 0.9072253940993811, w2: 0.8123622883456594, bias: -0.43008778933657643, loss: 0.6445647496037267
Epochs: 300, w1: 0.8905541770378377, w2: 0.7732792422482426, bias: -0.5674039089368744, loss: 0.6235884874764943
Epochs: 400, w1: 0.8866690182139638, w2: 0.7577106177939896, bias: -0.6715833952214005, loss: 0.6123250180601414
Epochs: 500, w1: 0.8916217256393004, w2: 0.7580849307948224, bias: -0.7527721627771985, loss: 0.6056380035701807
Epochs: 600, w1: 0.9025720198451935, w2: 0.7689020946348529, bias: -0.818222152769187, loss: 0.6010850762638486
Epochs: 700, w1: 0.9175611677034967, w2: 0.7863593092728112, bias: -0.8729167129225103, loss: 0.5975492681676184
Epochs: 800, w1: 0.9352654090990593, w2: 0.8078927076499592, bias: -0.920218039087977, loss: 0.59

In [83]:
coef, intercept

(array([[5.257192 ],
        [1.4094174]], dtype=float32),
 array([-3.019231], dtype=float32))

In [84]:
X_test

age  affordibility
2   0.47              1
18  0.19              0
8   0.62              1
7   0.60              0
0   0.22              1
17  0.58              1

2 = 1 ,
15 = 1 ,
17 = 1 ,
26 = 0 ,
27 = 0 ,
12 = 0


In [85]:
custom_model.predict(X_test)

2     0.813057
18    0.547358
8     0.834795
7     0.645656
0     0.772064
17    0.829205
dtype: float64

In [86]:
model.predict(X_test)

1/1 [==============================] - 0s 24ms/step


array([[0.7028834 ],
       [0.11708131],
       [0.8388431 ],
       [0.5337199 ],
       [0.3885927 ],
       [0.80835515]], dtype=float32)