<a href="https://colab.research.google.com/github/RifatMuhtasim/Deep_Learning/blob/main/Learn/40.Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
# Encode Reviews Using One Hot Encoding
vocab_size = 30
encoded_reviews = [one_hot(i, vocab_size) for i in reviews]
encoded_reviews

[[6, 11],
 [5, 29],
 [27, 1],
 [9, 21, 25],
 [13, 13, 16],
 [25, 11],
 [22, 13, 25],
 [21, 26],
 [21, 10],
 [7, 10]]

In [4]:
# Padding Reviews
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding="post")
print(padded_reviews)

[[ 6 11  0]
 [ 5 29  0]
 [27  1  0]
 [ 9 21 25]
 [13 13 16]
 [25 11  0]
 [22 13 25]
 [21 26  0]
 [21 10  0]
 [ 7 10  0]]


In [5]:
X = padded_reviews
y = sentiment

## Model building

In [6]:
embeded_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss="binary_crossentropy", metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.fit(X, y, epochs=50, verbose=0)

In [8]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 466ms/step - loss: 0.6202 - accuracy: 1.0000


1.0

In [9]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [12]:
# For "Nice" Word
weights[6]

array([-0.03763511, -0.085541  ,  0.02342713, -0.03204041, -0.0558969 ],
      dtype=float32)

In [13]:
# For "Amazing" word
weights[5]

array([-0.02467686, -0.03749996,  0.06040226, -0.03403303, -0.09791127],
      dtype=float32)